#!/usr/bin/env python3
"""
Build search/search_log.md and PRISMA Phase-1 counts from runner output.

Reads search/_run_summary.json and search/dedup_summary.json produced by
search_runner.py and deduplicate.py respectively, plus the raw JSON files
under data/raw_search_results/ to compute per-technique × per-database
contingency.

Stdlib only. Python 3.9+.
"""

from __future__ import annotations

import csv
import datetime
import json
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RUN_SUMMARY = REPO / "search" / "_run_summary.json"
DEDUP_SUMMARY = REPO / "search" / "dedup_summary.json"
RAW_DIR = REPO / "data" / "raw_search_results"
TAXONOMY_PATH = REPO / "taxonomy" / "techniques.md"
LOG_PATH = REPO / "search" / "search_log.md"


def parse_taxonomy_ids(path: Path) -> list[str]:
    import re
    text = path.read_text(encoding="utf-8")
    ids = re.findall(r"^###\s+`([a-z0-9\-]+)`", text, re.MULTILINE)
    return ids


def main() -> int:
    if not RUN_SUMMARY.exists():
        print(f"WARN: {RUN_SUMMARY} missing — runner did not write its summary.", file=sys.stderr)
        run_summary = {"started": "?", "finished": "?", "log": {}, "total": 0}
    else:
        run_summary = json.loads(RUN_SUMMARY.read_text())
    dedup = {}
    if DEDUP_SUMMARY.exists():
        dedup = json.loads(DEDUP_SUMMARY.read_text())
    taxonomy_ids = parse_taxonomy_ids(TAXONOMY_PATH)

    # Per-database × per-technique counts from raw files
    grid: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    databases_present: list[str] = []
    if RAW_DIR.exists():
        for db_dir in sorted(RAW_DIR.iterdir()):
            if not db_dir.is_dir():
                continue
            db = db_dir.name
            databases_present.append(db)
            for f in db_dir.glob("*.json"):
                tid = f.stem
                try:
                    rows = json.loads(f.read_text())
                    grid[db][tid] = len(rows)
                except Exception:
                    grid[db][tid] = 0

    # Build markdown
    out: list[str] = []
    out.append("# Search Log")
    out.append("")
    out.append(
        f"Auto-generated by `scripts/build_search_log.py` on "
        f"{datetime.datetime.utcnow().isoformat()}Z."
    )
    out.append("")
    out.append("Records the verbatim execution of `scripts/search_runner.py`. "
              "All search strings are pre-registered in `search/strategy.md`.")
    out.append("")
    # Compute total raw hits from on-disk JSON files (resilient to multi-pass runs)
    total_raw = 0
    if RAW_DIR.exists():
        for db_dir in RAW_DIR.iterdir():
            if db_dir.is_dir():
                for jf in db_dir.glob("*.json"):
                    try:
                        total_raw += len(json.loads(jf.read_text()))
                    except Exception:
                        pass
    out.append(f"- **Last runner pass started (UTC):** {run_summary.get('started', '?')}")
    out.append(f"- **Last runner pass finished (UTC):** {run_summary.get('finished', '?')}")
    out.append(f"- **Total raw hits across all passes:** {total_raw}")
    if dedup:
        out.append(f"- **After deduplication:** {dedup.get('unique_records', '?')} "
                   f"(ratio {dedup.get('dedup_ratio', '?')})")
        out.append(f"- **Multi-source unique records:** {dedup.get('multi_source_records', '?')}")
        out.append(f"- **With DOI:** {dedup.get('with_doi', '?')}")
        out.append(f"- **With abstract:** {dedup.get('with_abstract', '?')}")
    out.append("")

    # Per-database totals
    out.append("## Per-database totals")
    out.append("")
    out.append("| Database | Raw hits |")
    out.append("| --- | ---: |")
    for db in databases_present:
        total = sum(grid[db].values())
        out.append(f"| `{db}` | {total} |")
    out.append("")

    # Per-technique × database matrix
    if databases_present:
        out.append("## Per-technique × per-database matrix")
        out.append("")
        header = "| technique_id | " + " | ".join(databases_present) + " | total |"
        sep = "| " + " | ".join(["---"] * (len(databases_present) + 2)) + " |"
        out.append(header)
        out.append(sep)
        for tid in taxonomy_ids:
            row_total = 0
            cells: list[str] = []
            for db in databases_present:
                n = grid[db].get(tid, 0)
                cells.append(str(n))
                row_total += n
            out.append(f"| `{tid}` | " + " | ".join(cells) + f" | **{row_total}** |")
        out.append("")
        # zero-yield techniques (RQ-5 evidence)
        zeros = [tid for tid in taxonomy_ids
                 if all(grid[db].get(tid, 0) == 0 for db in databases_present)]
        if zeros:
            out.append("## Zero-yield techniques across all searched databases")
            out.append("")
            out.append("These techniques returned **zero records** across all "
                       "searched databases. This is direct evidence for RQ-5: "
                       "what proportion of named techniques have no empirical "
                       "literature?")
            out.append("")
            for tid in zeros:
                out.append(f"- `{tid}`")
            out.append("")

    out.append("## Notes")
    out.append("")
    out.append("- Hit counts above are pre-screening. Title-abstract screening (Stage 1) "
               "and full-text screening (Stage 2) follow per `search/inclusion_criteria.md`.")
    out.append("- The 200-hit ceiling on OpenAlex queries reflects the per-page API limit, "
               "not the true ceiling of relevant records. Forward citation chasing in Phase 2 "
               "captures records beyond the first page.")
    out.append("- ProQuest Dissertations metadata-only access via OAI-PMH is deferred to a "
               "later sub-session; not yet executed.")

    LOG_PATH.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"[log] Wrote {LOG_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
